version: '2'
services:
  postgresdb:
    restart: always
    env_file:
        - etc/config.env
    image: 'postgres:9.4'
    expose:
      - 5432

  async-aloha:
    restart: always
    image: 'async-aloha:latest'
    env_file:
        - etc/config.env
    links:
      - postgresdb:postgresdb
    depends_on:
      - postgresdb
    ports:
      - '8080:9989'
    volumes:
      - './logs:/async-aloha/logs:rw'

# Openstack network default mtu fix
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
